//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant.Localization.SourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resturant.Localization.SourceFiles.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to accept this task?.
        /// </summary>
        public static string ConfirmAcceptTaskMessage {
            get {
                return ResourceManager.GetString("ConfirmAcceptTaskMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to activate this {0} ?.
        /// </summary>
        public static string ConfirmActivateObject {
            get {
                return ResourceManager.GetString("ConfirmActivateObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to Active this {0} ?.
        /// </summary>
        public static string ConfirmActiveObject {
            get {
                return ResourceManager.GetString("ConfirmActiveObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to deactivate this {0} ?.
        /// </summary>
        public static string ConfirmDeactivateObject {
            get {
                return ResourceManager.GetString("ConfirmDeactivateObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete this {0} ?.
        /// </summary>
        public static string ConfirmDeleteObject {
            get {
                return ResourceManager.GetString("ConfirmDeleteObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reject this task?.
        /// </summary>
        public static string ConfirmRejectTaskMessage {
            get {
                return ResourceManager.GetString("ConfirmRejectTaskMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to unassigned this {0} ?.
        /// </summary>
        public static string ConfirmUnassignedObject {
            get {
                return ResourceManager.GetString("ConfirmUnassignedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be numeric..
        /// </summary>
        public static string InputMustBeNumeric {
            get {
                return ResourceManager.GetString("InputMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was Activated successfully.
        /// </summary>
        public static string ObjectActivatedSuccessfully {
            get {
                return ResourceManager.GetString("ObjectActivatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was added successfully.
        /// </summary>
        public static string ObjectAddedSuccessfully {
            get {
                return ResourceManager.GetString("ObjectAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} assigned successfully.
        /// </summary>
        public static string ObjectAssignedSuccessfully {
            get {
                return ResourceManager.GetString("ObjectAssignedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was deactivated successfully.
        /// </summary>
        public static string ObjectDeActivatedSuccessfully {
            get {
                return ResourceManager.GetString("ObjectDeActivatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was deleted successfully.
        /// </summary>
        public static string ObjectDeleedSuccessfully {
            get {
                return ResourceManager.GetString("ObjectDeleedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Was Reset Successfully.
        /// </summary>
        public static string ObjectResetSuccessfully {
            get {
                return ResourceManager.GetString("ObjectResetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Was Submited Successfully.
        /// </summary>
        public static string ObjectSubmitSuccessfully {
            get {
                return ResourceManager.GetString("ObjectSubmitSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} unassigned successfully.
        /// </summary>
        public static string ObjectUnassignedSuccessfully {
            get {
                return ResourceManager.GetString("ObjectUnassignedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} unassigned successfully.
        /// </summary>
        public static string ObjectUnassignedSuccessfully1 {
            get {
                return ResourceManager.GetString("ObjectUnassignedSuccessfully1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Was UnLocked Successfully.
        /// </summary>
        public static string ObjectUnLockedSuccessfully {
            get {
                return ResourceManager.GetString("ObjectUnLockedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was updated successfully.
        /// </summary>
        public static string ObjectUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ObjectUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task   was Accepted successfully.
        /// </summary>
        public static string TaskAcceptedSuccessfully {
            get {
                return ResourceManager.GetString("TaskAcceptedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task   was Completed successfully.
        /// </summary>
        public static string TaskCompletedSuccessfully {
            get {
                return ResourceManager.GetString("TaskCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task  was Rejected successfully.
        /// </summary>
        public static string TaskRejectedSuccessfully {
            get {
                return ResourceManager.GetString("TaskRejectedSuccessfully", resourceCulture);
            }
        }
    }
}
